name: flutter_weather_demo
description: A new Flutter project.
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: any
  http: any
  rxdart: ^0.23.1
  rx_command: 
    path: ..\

dev_dependencies:
  build_runner: ^0.10.1+1
  json_serializable: ^1.1.0

flutter:
  uses-material-design: true
