name: rx_command
description: Reactive event handler wrapper class inspired by ReactiveUI.
version: 2.0.4
maintainer: Thomas Burkhart (@escamoteur)
authors:
- Flutter Community <community@flutter.zone>
- Thomas Burkhart <burkhartsengineering@gmail.com>
homepage: https://github.com/fluttercommunity/rx_command
documentation:
environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  rxdart: ^0.18.0
  quiver_hashcode: ^2.0.0
  json_annotation: ^0.2.3

dev_dependencies:
  quiver: ^0.29.0
  flutter_test:
    sdk: flutter
